# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_inter(object):
    def setupUi(self, MainWindow_inter):
        MainWindow_inter.setObjectName("MainWindow_inter")
        MainWindow_inter.resize(819, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow_inter)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(236, 236, 238);\n"
"border-radius:30px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-top-left-radius:30px;\n"
"    border-top-right-radius:30px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_min = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_min.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/small - 副本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon)
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_2.addWidget(self.pushButton_min)
        self.pushButton_max = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_max.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton_max.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/big - 副本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_max.setIcon(icon1)
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_2.addWidget(self.pushButton_max)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_close.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/close1 - 副本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon2)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.horizontalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_scrapy = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_scrapy.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_scrapy.setFont(font)
        self.pushButton_scrapy.setStyleSheet("QPushButton{\n"
"background-color: rgb(236, 236, 238);\n"
"border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_scrapy.setIcon(icon3)
        self.pushButton_scrapy.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_scrapy.setObjectName("pushButton_scrapy")
        self.verticalLayout_2.addWidget(self.pushButton_scrapy)
        self.pushButton_ai = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_ai.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ai.setFont(font)
        self.pushButton_ai.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_ai.setStyleSheet("QPushButton{\n"
"background-color: rgb(236, 236, 238);\n"
"border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/ai.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ai.setIcon(icon4)
        self.pushButton_ai.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_ai.setObjectName("pushButton_ai")
        self.verticalLayout_2.addWidget(self.pushButton_ai)
        self.pushButton_contact = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_contact.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_contact.setFont(font)
        self.pushButton_contact.setStyleSheet("QPushButton{\n"
"background-color: rgb(236, 236, 238);\n"
"border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_contact.setIcon(icon5)
        self.pushButton_contact.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_contact.setObjectName("pushButton_contact")
        self.verticalLayout_2.addWidget(self.pushButton_contact)
        self.pushButton_user = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_user.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_user.setFont(font)
        self.pushButton_user.setStyleSheet("QPushButton{\n"
"background-color: rgb(236, 236, 238);\n"
"border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_user.setIcon(icon6)
        self.pushButton_user.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_user.setObjectName("pushButton_user")
        self.verticalLayout_2.addWidget(self.pushButton_user)
        self.horizontalLayout_4.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setStyleSheet("background-color: rgb(225, 225, 227);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.output_scrapy = QtWidgets.QTextBrowser(self.frame_7)
        self.output_scrapy.setGeometry(QtCore.QRect(160, 170, 256, 192))
        self.output_scrapy.setObjectName("output_scrapy")
        self.Go = QtWidgets.QPushButton(self.frame_7)
        self.Go.setGeometry(QtCore.QRect(380, 40, 31, 31))
        self.Go.setStyleSheet("background-color: rgb(0, 174, 236);\n"
"border-radius:5px")
        self.Go.setObjectName("Go")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.input_scrapy = QtWidgets.QLineEdit(self.frame_7)
        self.input_scrapy.setGeometry(QtCore.QRect(200, 40, 161, 31))
        self.input_scrapy.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.input_scrapy.setText("")
        self.input_scrapy.setObjectName("input_scrapy")
        self.verticalLayout_3.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_8 = QtWidgets.QFrame(self.page_4)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 604, 387))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.output_ai = QtWidgets.QTextBrowser(self.frame_8)
        self.output_ai.setGeometry(QtCore.QRect(75, 121, 461, 251))
        self.output_ai.setObjectName("output_ai")
        self.Go_2 = QtWidgets.QPushButton(self.frame_8)
        self.Go_2.setGeometry(QtCore.QRect(380, 40, 31, 31))
        self.Go_2.setStyleSheet("background-color: rgb(0, 174, 236);\n"
"border-radius:5px")
        self.Go_2.setObjectName("Go_2")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setGeometry(QtCore.QRect(270, 10, 54, 12))
        self.label.setObjectName("label")
        self.input_ai = QtWidgets.QLineEdit(self.frame_8)
        self.input_ai.setGeometry(QtCore.QRect(200, 40, 161, 31))
        self.input_ai.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.input_ai.setText("")
        self.input_ai.setObjectName("input_ai")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(210, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 100, 291, 31))
        self.lineEdit_11.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(130, 170, 291, 31))
        self.lineEdit_12.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(130, 270, 291, 21))
        self.lineEdit_13.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(440, 270, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow_inter.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_inter)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_min.clicked.connect(MainWindow_inter.showMinimized) # type: ignore
        self.pushButton_max.clicked.connect(MainWindow_inter.showMaximized) # type: ignore
        self.pushButton_close.clicked.connect(MainWindow_inter.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow_inter)

    def retranslateUi(self, MainWindow_inter):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_inter.setWindowTitle(_translate("MainWindow_inter", "MainWindow"))
        self.pushButton_scrapy.setText(_translate("MainWindow_inter", "Search "))
        self.pushButton_ai.setText(_translate("MainWindow_inter", "AI     "))
        self.pushButton_contact.setText(_translate("MainWindow_inter", "Contact"))
        self.pushButton_user.setText(_translate("MainWindow_inter", "User   "))
        self.Go.setText(_translate("MainWindow_inter", "Go"))
        self.label_2.setText(_translate("MainWindow_inter", "Scarpy"))
        self.input_scrapy.setPlaceholderText(_translate("MainWindow_inter", "name:"))
        self.Go_2.setText(_translate("MainWindow_inter", "Go"))
        self.label.setText(_translate("MainWindow_inter", "AI"))
        self.input_ai.setPlaceholderText(_translate("MainWindow_inter", "name:"))
        self.label_3.setText(_translate("MainWindow_inter", "Contact us"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow_inter", "Your name:"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow_inter", "Email:"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow_inter", "Message:"))
        self.pushButton.setText(_translate("MainWindow_inter", "Submit"))
import weat_rc
